### ISSUE TITLE
Question: Service Manager is required but not fully utilized

### ISSUE THREAD

**Issue by internalsystemerror** [xtreamwayz/expressive-messenger#45]
Is the intention of this project to move `laminas/laminas-service-manager` from `"required"` to `"require-dev"`?

Either:
- This should be the case, so that other PSR-11 containers can use the provided factories (as I believe would currently be the case).
- Or the third argument provided to `__invoke()` on the factories: `string $requestedName`, should be used in place of class names where possible, to allow factories to be reused.

**Comment by geerteltink** [comment]
The idea is that it should be possible to use other PSR-11 containers as well. However I never tried it and the factories might need a change. I have to test against different containers and see what changes need to be made and if it is even possible.

**Comment by internalsystemerror** [comment]
I'm in favour of that option. As it stands, moving `laminas/laminas-service-manager` from `"required"` to `"require-dev"`, shouldn't break anything as there no references to anything `Laminas` within `src`. I'm in the same boat where I'm unfamiliar with other container implementations so I'm not sure how they would be able to reuse the configuration in `ConfigProvider`.

**Comment by geerteltink** [comment]
I've added integration tests for all official supported containers. They all seem to work with this package.

About your original question:

> Is the intention of this project to move `laminas/laminas-service-manager` from `"required"` to `"require-dev"`?

It is not in the `require` section but in the `require-dev` section. I also checked the docs and it doesn't mention (I think) something about the service manager requirement. The only requirements is `psr/container` and obviously the Symfony packages.

So I guess it supports 
- Servicemanager (laminas-servicemanager)
- Pimple (laminas-pimple-config)
- Aura.Di (laminas/laminas-auradi-config)

Probably the non official containers are supported as well which you can install with the mezzio-skeleton. They convert the standard mezzio configuration to something that the container understands. Other PSR-11 containers are going to be difficult as there is no PSR for container configuration and might miss some logic to use the Factories that are used here.

**Comment by internalsystemerror** [comment]
Totally missed that, my apologies.
